version: 2
jobs:
  clojure:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          command: lein run circleci
          #no_output_timeout works around the following error.
          #Too long with no output (exceeded 20m0s)
          no_output_timeout: 2400
      - persist_to_workspace:
          root: .
          paths:
            - resources/kubernetes/kubernetes.txt
  gcloud:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: script/gcloud.sh
workflows:
  version: 2
  workflow:
    jobs:
      - clojure:
          filters:
            tags:
              only: /.+/
      - gcloud:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.+/
          requires:
            - clojure
