version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein@sha256:db71a785f4b39c2fb6802808c0efd4f586172b3ef487ec3af235f57c49320df8
    steps:
      - checkout
      - restore_cache:
          keys:
          - .m2-{{checksum "project.clj"}}
      - run: lein test && lein uberjar
      - save_cache:
          paths:
            - ~/.m2
          key: .m2-{{checksum "project.clj"}}
