version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein
    steps:
      - checkout
      - restore_cache:
          keys:
          - .m2-{{checksum "project.clj"}}
      - run: lein test && lein uberjar
      - save_cache:
          paths:
            - ~/.m2
          key: .m2-{{checksum "project.clj"}}
