version: 2
jobs:
  clojure:
    docker:
      - image: circleci/clojure:lein-2.8.1-node@sha256:1d232488cb86d9174393202867bb2a4d1229edc7dd602eda69025fb99954c92a
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: lein run circleci
          #no_output_timeout works around the following error.
          #Too long with no output (exceeded 10m0s)
          no_output_timeout: 1200
      - persist_to_workspace:
          root: .
          paths:
            - kubernetes.txt
            - dev-resources/docker
            - script/docker.sh
  machine:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: script/docker.sh
  gcloud:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: script/gcloud.sh
workflows:
  version: 2
  workflow:
    jobs:
      - clojure:
          filters:
            tags:
              only: /.+/
      - machine:
          filters:
            tags:
              only: /.+/
          requires:
            - clojure
      - gcloud:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.+/
          requires:
            - clojure
            - machine
