version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein@sha256:db71a785f4b39c2fb6802808c0efd4f586172b3ef487ec3af235f57c49320df8
    steps:
      - checkout
      - setup_remote_docker
      - run: |
         lein test &&
         lein cljsbuild once prod &&
         lein uberjar &&
         docker build -f docker/clojure/Dockerfile .
