version: 2
jobs:
  uberjar:
    docker:
      - image: circleci/clojure:lein-2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - .m2-{{checksum "project.clj"}}
      - run: lein test
      - save_cache:
          paths:
            - ~/.m2
          key: .m2-{{checksum "project.clj"}}
      - run: lein uberjar
      - persist_to_workspace:
          root: target/uberjar
          paths: main.jar
workflows:
  version: 2
  clojure:
    jobs:
      - uberjar
