version: 2
jobs:
  uberjar:
    docker:
      - image: clojure:lein
    steps:
      - checkout
      - restore_cache:
          keys:
          - .m2-{{checksum "project.clj"}}
      - run: lein test && lein uberjar
      - save_cache:
          paths:
            - ~/.m2
          key: .m2-{{checksum "project.clj"}}
      - persist_to_workspace:
          root: .
          paths: target/uberjar/main.jar
workflows:
  version: 2
  clojure:
    jobs:
      - uberjar
