version: 2
jobs:
  clojure:
    docker:
      - image: circleci/clojure:lein@sha256:db71a785f4b39c2fb6802808c0efd4f586172b3ef487ec3af235f57c49320df8
    steps:
      - checkout
      - setup_remote_docker
      - run: lein run circleci
      - persist_to_workspace:
          root: resources
          paths:
            - kubernetes.txt
  gcloud:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: script/gcloud.sh
workflows:
  version: 2
  workflow:
    jobs:
      - clojure:
          filters:
            tags:
              only: /.+/
      - gcloud:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.+/
          requires:
            - clojure
