version: 2
jobs:
  clojure:
    docker:
      - image: circleci/clojure:lein-2.8.1-node
    steps:
      - checkout
      - setup_remote_docker
      - run: lein run circleci
      - persist_to_workspace:
          root: .
          paths:
            - kubernetes.txt
  gcloud:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: script/gcloud.sh
workflows:
  version: 2
  workflow:
    jobs:
      - clojure:
          filters:
            tags:
              only: /.+/
      - gcloud:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.+/
          requires:
            - clojure
